services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString

databases:
  - name: n8n
    plan: free
